apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: My Homelab Dashboard
    theme: dark
  bookmarks.yaml: |
    - Infrastructure:
        - GitHub Repository:
            - abbr: GH
              href: https://github.com/ajdann/homelab
  services.yaml: |
    - Core Services:
        - Kubernetes Dashboard:
            href: http://localhost/
            description: Kubernetes cluster management
        - Kured:
            href: http://localhost/
            description: Kubernetes Node Reboot Daemon

    - Applications:
        - Homepage:
            href: http://localhost/
            description: This dashboard
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "Homelab Cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
