---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  namespace: homepage
  annotations:
    tailscale.com/tags: tag:k8s-operator
spec:
  ingressClassName: tailscale
  rules:
  - host: homepage
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homepage
            port:
              number: 80
  tls:
  - hosts:
    - homepage
