---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
# - ingress.yaml  # Temporarily commented out until Traefik is installed
- rbac.yaml
- configmap.yaml
