---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- rbac.yaml
- configmap.yaml

configMapGenerator:
- name: common-versions
  behavior: merge
  files:
  - ../../common/versions.yaml

vars:
- name: security.runAsUser
  objRef:
    kind: ConfigMap
    name: common-versions
    apiVersion: v1
  fieldRef:
    fieldPath: data.security.runAsUser
- name: security.runAsGroup
  objRef:
    kind: ConfigMap
    name: common-versions
    apiVersion: v1
  fieldRef:
    fieldPath: data.security.runAsGroup
- name: security.fsGroup
  objRef:
    kind: ConfigMap
    name: common-versions
    apiVersion: v1
  fieldRef:
    fieldPath: data.security.fsGroup
- name: versions.homepage.image
  objRef:
    kind: ConfigMap
    name: common-versions
    apiVersion: v1
  fieldRef:
    fieldPath: data.versions.homepage.image
- name: versions.homepage.version
  objRef:
    kind: ConfigMap
    name: common-versions
    apiVersion: v1
  fieldRef:
    fieldPath: data.versions.homepage.version
- name: resources.small.requests.cpu
  objRef:
    kind: ConfigMap
    name: common-versions
    apiVersion: v1
  fieldRef:
    fieldPath: data.resources.small.requests.cpu
- name: resources.small.requests.memory
  objRef:
    kind: ConfigMap
    name: common-versions
    apiVersion: v1
  fieldRef:
    fieldPath: data.resources.small.requests.memory
- name: resources.small.limits.cpu
  objRef:
    kind: ConfigMap
    name: common-versions
    apiVersion: v1
  fieldRef:
    fieldPath: data.resources.small.limits.cpu
- name: resources.small.limits.memory
  objRef:
    kind: ConfigMap
    name: common-versions
    apiVersion: v1
  fieldRef:
    fieldPath: data.resources.small.limits.memory
