---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps
  - ../../core

configMapGenerator:
  - name: global-vars
    literals:
      - domain=dev-tail1345c.ts.net
