---
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-oauth
  namespace: tailscale
type: Opaque
stringData:
  clientId: "" # Will be populated by Flux
  clientSecret: "" # Will be populated by Flux 
