apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-bootstrap
  namespace: authentik
data:
  ak.yaml: |
    version: 1
    blueprints:
      - name: gitea-oauth-provider
        model: authentik_providers_oauth2.oauth2provider
        identifiers:
          name: gitea
        attrs:
          name: gitea
          client_id: u4QfKMnaRrcfipiNKOnrihhhA5U9Ik8shlhTviL6
          client_secret: UuWVUFWxY2Z9CA2F9BLNSnw4zpY46V84MTXMSGe6Tslx8h2y8rWefZIspMsvVQ97zKH0UnJlVepU2RmGdhiMjzMeY1i9AuKZzMrAIAKqBFGYqnT1nxUuT1GANDWds1RP
          authorization_flow: default-provider-authorization-implicit-consent
          redirect_uris:
            - https://gitea/user/oauth2/authentik/callback
          signing_key: default
          access_token_validity: 3600
          refresh_token_validity: 86400
          property_mappings:
            - name: ak_email_mapping
              property_mapping: ak_oauth2_scope_email
            - name: ak_profile_mapping
              property_mapping: ak_oauth2_scope_profile

      - name: gitea-application
        model: authentik_core.application
        identifiers:
          name: gitea
        attrs:
          name: Gitea
          slug: gitea
          provider: !BlueprintRef gitea-oauth-provider
          protocol: oauth2
          authorization_flow: default-application-authentication-flow
          redirect_uris:
            - https://gitea/user/oauth2/authentik/callback
          meta_launch_url: https://gitea
          open_in_new_tab: true
