apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-app
  namespace: authentik
data:
  gitea-app.yaml: |
    version: 1
    blueprints:
      - name: gitea-app
        model: authentik_core.application
        identifiers:
          name: gitea-app
        attrs:
          name: Gitea App
          slug: gitea-app
          provider: gitea
          protocol: oauth2
          authorization_flow: default-provider-authorization-implicit-consent
          redirect_uris:
            - https://gitea.local/user/oauth2/authentik/callback
          meta_launch_url: https://gitea.local
          open_in_new_tab: true