---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: '2025.6.4'
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: authentik
  values:
    blueprints:
      configMaps:
      - gitea-app
      - gitea-property-mappings
      - gitea-groups
      - nextcloud-property-mappings
      - nextcloud-app
      secrets:
      - gitea-provider
      - nextcloud-provider
    authentik:
      secret_key: 'PleaseGenerateASecureKey'
      postgresql:
        user: authentik
        password: 'LKz0EYm4iv'
      error_reporting:
        enabled: true
    server:
      ingress:
        annotations:
          tailscale.com/tags: tag:k8s-operator
          gethomepage.dev/enabled: 'true'
          gethomepage.dev/name: 'Authentik'
          gethomepage.dev/description: 'Authentik'
          gethomepage.dev/group: 'Administration'
          gethomepage.dev/icon: 'authentik.png'
          gethomepage.dev/href: 'https://authentik.${DOMAIN}'
          # gethomepage.dev/widget.type: 'kubernetes'
          # gethomepage.dev/widget.url: 'https://authentik.${DOMAIN}'
          # gethomepage.dev/pod-selector: 'app.kubernetes.io/name=authentik'
        ingressClassName: tailscale
        enabled: true
        https: true
        tls:
        - hosts:
          - authentik
        hosts:
        - authentik
    postgresql:
      auth:
        username: authentik
        password: 'LKz0EYm4iv' 
      enabled: true
    redis:
      enabled: true
