---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik
resources:
- namespace.yaml
- helm-repository.yaml
- helm-release.yaml
- ./gitea/application.yaml
- ./gitea/property-mappings.yaml
- ./gitea/groups.yaml
- ./nextcloud/property-mappings.yaml
- ./nextcloud/application.yaml
