---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik
resources:
- namespace.yaml
- helm-repository.yaml
- helm-release.yaml
- ./gitea/gitea-app.yaml
- ./gitea/gitea-provider.yaml
- ./gitea/gitea-property-mappings.yaml
- ./gitea/gitea-groups.yaml
