# Load configuration and helper files
require_relative 'vagrant/config/vm_resources'
require_relative 'vagrant/lib/helpers'

# Load all VM configuration files
Dir[File.join(File.dirname(__FILE__), 'vagrant/vms/*.rb')].each { |file| require file }

Vagrant.configure("2") do |config|
  # Configure each VM type
  configure_pfsense(config)
  configure_nessus(config)
  configure_haproxy(config)
  configure_k3s_master(config)
  configure_k3s_workers(config)
end