resources:
  - gitea-admin.yaml
  - gitea-authentik.yaml
  # - tailscale-oauth.yaml
  # - seafile.yaml
  - nextcloud-admin.yaml
  - gitea-authentik-provider.yaml
  - nextcloud-authentik-provider.yaml
