apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-provider
  namespace: authentik
stringData:
  nextcloud-provider.yaml: |
    # yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
    version: 1
    metadata:
      name: nextcloud
    entries:
      - model: authentik_providers_oauth2.oauth2provider
        state: present
        identifiers:
          name: nextcloud
        attrs:
          name: nextcloud
          client_id: "nextcloud-6f9a3b1b2d"
          client_secret: "UuWVUFWxY2Z9CA2F9BLNSnw4zpY46V84MTXMSGe6Tslx8h2y8rWefZIspMsvVQ97zKH0UnJlVepU2RmGdhiMjzMeY1i9AuKZzMrAIAKqBFGYqnT1nxUuT1GANDWds1RP"
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
          invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
          redirect_uris:
            - url: https://nextcloud.tail1345c.ts.net/user/oauth2/authentik/callback
              matching_mode: strict
          signing_key: !Find [authentik_crypto.certificatekeypair, [name, default]]
          access_token_validity: hours=1
          refresh_token_validity: days=1
          include_in_api: true
          token_validity: hours=1
          include_claims_in_id_token: true
          sub_mode: hashed_user_id
          property_mappings:
            - !Find [authentik_providers_oauth2.scopemapping, [name, "authentik default OAuth Mapping: OpenID 'email'"]]
            - !Find [authentik_providers_oauth2.scopemapping, [name, "authentik default OAuth Mapping: OpenID 'profile'"]]
            - !Find [authentik_providers_oauth2.scopemapping, [name, "authentik default OAuth Mapping: OpenID 'openid'"]]
            - !Find [authentik_providers_oauth2.scopemapping, [name, "Nextcloud Profile"]]
