all:
  hosts:
    localhost:
      ansible_connection: local

    proxmox:
      ansible_host: 192.168.1.157   # Proxmox node IP
      ansible_user: root
      ansible_connection: ssh
      ansible_password: 12345678
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'


    debian12-cloudinit:
      ansible_host: 192.168.1.200
      ansible_user: ansible
      ansible_password: securepassword