all:
  hosts:
    localhost:
      ansible_connection: local

    proxmox:
      ansible_host: 192.168.1.157   # Proxmox node IP
      ansible_user: root
      ansible_connection: ssh
      ansible_password: "{{ lookup('file', playbook_dir + '/../../secrets/proxmox_api_password') }}"
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    k3s-master-1:
      ansible_host: 192.168.1.200
      ansible_user: "{{ lookup('file', playbook_dir + '/../../secrets/ansible_user') }}"
      ansible_password: "{{ lookup('file', playbook_dir + '/../../secrets/ansible_password') }}"

    k3s-master-2:
      ansible_host: 192.168.1.201
      ansible_user: "{{ lookup('file', playbook_dir + '/../../secrets/ansible_user') }}"
      ansible_password: "{{ lookup('file', playbook_dir + '/../../secrets/ansible_password') }}"

    k3s-master-3:
      ansible_host: 192.168.1.202
      ansible_user: "{{ lookup('file', playbook_dir + '/../../secrets/ansible_user') }}"
      ansible_password: "{{ lookup('file', playbook_dir + '/../../secrets/ansible_password') }}"

    haproxy-1:
      ansible_host: 192.168.1.203
      ansible_user: "{{ lookup('file', playbook_dir + '/../../secrets/ansible_user') }}"
      ansible_password: "{{ lookup('file', playbook_dir + '/../../secrets/ansible_password') }}"

    haproxy-2:
      ansible_host: 192.168.1.204
      ansible_user: "{{ lookup('file', playbook_dir + '/../../secrets/ansible_user') }}"
      ansible_password: "{{ lookup('file', playbook_dir + '/../../secrets/ansible_password') }}"

  children:
    k3s_masters:
      hosts:
        k3s-master-1:
        k3s-master-2:
        k3s-master-3:

    haproxy_nodes:
      hosts:
        haproxy-1:
        haproxy-2: