apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: "24.0.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 1m
  values:
    deployment:
      replicas: 1
    service:
      type: NodePort
    ports:
      web:
        nodePort: 30080
      websecure:
        nodePort: 30443
    ingressRoute:
      dashboard:
        enabled: true
    dashboard:
      enabled: true 