---

- name: Install HAProxy and Keepalived
  apt:
    name:
      - haproxy
      - keepalived
    state: present
    update_cache: yes

- name: Configure HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: Validate HAProxy configuration
  command: haproxy -c -f /etc/haproxy/haproxy.cfg
  register: haproxy_validation
  changed_when: false
  failed_when: haproxy_validation.rc != 0

- name: Show HAProxy configuration errors
  debug:
    var: haproxy_validation.stderr
  when: haproxy_validation.rc != 0

- name: Configure Keepalived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: restart keepalived

- name: Ensure HAProxy service is started and enabled
  service:
    name: haproxy
    state: started
    enabled: yes

- name: Ensure Keepalived service is started and enabled
  service:
    name: keepalived
    state: started
    enabled: yes
