apiVersion: ENC[AES256_GCM,data:P/nsQMhtov0jCMH3saZtXSutemTnQKisgIvK0j1C,iv:hu+Llp0h5C9D58SmG33q01U78Y9tTQDwIv76IBLxFKI=,tag:wDDreLNzgvDOq/w4bT92wQ==,type:str]
kind: ENC[AES256_GCM,data:EwIIEEl6W1TTijQ=,iv:3C38qyliX9ylse2BMAR7OJ0LNNWNM8jhhFiC22TVJcg=,tag:uCVZ2tsFqUJJu9wrpd7H3A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QQwTOv1z8hpq,iv:Upk6sscBzHJpc3F+hRNUlRys3lcYpfvUcyCqnnz8tz4=,tag:GmuXX2CMqGQzMpU+MZEY/A==,type:str]
    namespace: ENC[AES256_GCM,data:fKCu3I9p5fyB,iv:Nkna4b9wXtn60IUAdQV0N0wNxSEcU/XbHL6CmMVIZTU=,tag:xOTpjZh1hLGqoYZd8VqLAw==,type:str]
spec:
    values:
        authentik:
            #ENC[AES256_GCM,data:yMFMfQpZYQxfBTg4HrrUwtqFFcc=,iv:Rq60QNHyY8/X2otxwuBuAIJURcus+cC9dzl2kqMpfgQ=,tag:NV9J+lCEBNQJrLP50BxBAA==,type:comment]
            secret_key: ENC[AES256_GCM,data:JFxL/jk75rbL6I+XPZ6ueK76/nGTi3EA,iv:fQQmHPqtewNXkKdgPyI2lcr5kOrsZbJtnTMw1+bTmEw=,tag:AWJ1cqcUEr8/JNVAk9dnmw==,type:str]
            postgresql:
                password: ENC[AES256_GCM,data:G94sOUCvlh8StHBfv4Mq880NDwGdLIjs,iv:5raf5Ynzt6uB6keaaXy6JwIxS0ZbKEg7EqMDc1m/5Wo=,tag:2if0PPaYUpiCnBj5KqUzBg==,type:str]
        postgresql:
            auth:
                password: ENC[AES256_GCM,data:Jazl2uD/v7FErE7D0ofBXjlc2zqqGQqV,iv:XnBP3QjmWLtLDR9cWusK2T/yjArlOUXqNieE60grTRc=,tag:+zeIKX62YQaFcdvCOUNknQ==,type:str]
sops:
    age:
        - recipient: age1gzdqfgl6ww3en650g4dvtuejc0jrye60t7y34fxw6vm2mpj5g32quareev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFaURiS1JkZXNpQ3JDQlp4
            cGhvY1JBRVRvRmUxNDBaTlJneG9WVHJrMEZZCm9SaHMzSE9PdUdkL2IvL21OS2U0
            WjVLdlc2T0hMQW9lSi9kV1VLRWNRUDQKLS0tIHlmQ3BxMWd6VlFlMWMrY2hkNTUx
            SEppajV4eVhaeS94R1Q0YS9kbjNLbGMKTYqj3hDtPpYS1J8NsdCTpNTT+W0NvCYh
            0cOIxpcwrfAcWJ2D2+nz18VM/WVylFYBNQ7iPdQVtXuTVtQSGmJsFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T14:03:30Z"
    mac: ENC[AES256_GCM,data:uUapHAwe1jUwsIFM+ybrY9qMGoJIRneBntkQlTVCZItMSqEsnXNVDdgDbEXYk2jUArL4TbuAq/BDmIIeHyKxlmO4sil7d4POMkx/Tz/S10SamZWMXtK+MRWhdsCKmo1YbT6YH7HzhpDzsWhh3A3Oi2srfrwTowZEJrV0nJepoz4=,iv:dk7RjMUalZ0RdWmko0xdeotrvBY5Uy7aZ2DIBzGvDQU=,tag:0wh+vqkFcjsjhk+547RPKA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
