apiVersion: ENC[AES256_GCM,data:JyQ=,iv:CJR/JBOTEDi5UaZShQ3AiFJQ+mBK0eA1IH8zYNX39eg=,tag:EATF7hjHrVfRwX6IioC1gg==,type:str]
kind: ENC[AES256_GCM,data:3p5BQll2XLG0,iv:56HKDGMphNMWL6LYcI3Bi63sGyxGYaEn+6Okp0rUaRw=,tag:JoEIkxrl1OZb6xhRrXLWuw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Yuuq3wmBHOt9454iZsI=,iv:sWxba8n0q/0CopAqmSUkzoRAZ++QN+jC0NNYHDvp32E=,tag:w5/bpkGJTjVVy1QmoGh60Q==,type:str]
    namespace: ENC[AES256_GCM,data:bMgI+DUQHsc7,iv:+rEFHR9J49kH/KyPZBc3TkPXt6lKWm9AOLDzaCSlSoM=,tag:SJqWM7bJb2rfVW/E9ZCQcg==,type:str]
data:
    gitea-provider.yaml: ENC[AES256_GCM,data:fvumpfPsOF5rPBjuyaaeUcURyqRg07LkwGGmaZZhOAzQsoGzyh89/yf/77Nxv3TsGzpjtlcRX4iono3QoXbABeyaYm0F299Qepxn3sJKc1zUVQ5Y2pkz5pJjswVw/k4SE/J3uyoe146cK6mW4ghQg/2ZgCes+vA7hX4JE8MBkJvxi3aTGcqoo1mBU3+wsLdnGlQyxcL8VNssH8H1EbITgvE5BL3dc9mbCWCk/VbY+kZWDpbSl99r9PCSrP5E5l0yn9WV8CX4amEYtZDnmDwjOyV9/vHYqGPKdZCszQbPFKcx4wAFKlsh+itvzBz0olLjz8A04lJyOLd35Oh5LI/jkWo3t7GTTFpaRpYUZoXI15jjlYvRxpFjIBhsPJhAZ8HgNXEkVravLc2Wj00gBX+/vsEInF8N2Bb/OeJGu1Ec63FNNhrq1xyhSfhY,iv:wX7w7A6PdG1WDcRHEd/WPSdD3yvzHXTN5b7ltomB2c8=,tag:jKi7Lq52nKcfDQw0AkxE2g==,type:str]
sops:
    age:
        - recipient: age1gzdqfgl6ww3en650g4dvtuejc0jrye60t7y34fxw6vm2mpj5g32quareev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMd2haMmcreG1Ya0VHYmZN
            VzJZdTFoVTR6K3dUak9pL1p0MVNsMitvS25jCnNqa05yTW52TExPUjkxNUowcklQ
            b0FCYzdQb2d5YkhYNlF6bFZYWXJmejAKLS0tIGhBWk5mYnJaK2VZZTVIQUoyTm05
            VnIybDJxQThjTHZIYS9hNDh2N29QNlEKF6a45qS18oSoBlwhZJBACqx3X/eGmjUq
            Ie4BcxQmXBR4GnzY+KLCHGbGIVf54whCmEgqo4IyTy2VsXOoVqhCeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T14:03:36Z"
    mac: ENC[AES256_GCM,data:DjMOWJy410o0QqPYC3b17EHxt6tmW+eutnNLCGahUzSh2srjByrpMWYrd0MXCcQz4Xk8Y47c6oy7szfTsc9Hfnz/1R16JIoc6IYY3nOqg+hkJ30w1wAgca515emH2aOt9gdsSSVlN+FKY8OGPnS3Estw+MOOC8g5N39rfUWakfg=,iv:F7C45OEDR8qu160KbbuiY12CB73ycF8a7HONz8et2jE=,tag:UPswa0a1vfG6F7C5lIYAyA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
