apiVersion: ENC[AES256_GCM,data:6lw=,iv:Rxcjv8gyQREAlFCBDXJi0JUNra3RaPL9vcoiyLGcMHg=,tag:U++CDkof5nRLPfS5ug0eMQ==,type:str]
kind: ENC[AES256_GCM,data:7MkIl5PE,iv:ZwtLO8teClSWzL1SyU6NiD6FSgcgRphYANIcnzFV8ic=,tag:52YUHcmN4IlitfqaHVO9sQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hDd5veCGPePo28i54lqF,iv:B54nsePbMiaMAhhdD6dzygBFHHa5wNVBRJgoaSGJ7co=,tag:4ufMCkQcVq19x1hOUni0WQ==,type:str]
    namespace: ENC[AES256_GCM,data:+F9veEumS/LR,iv:TfZ7RcPaB7CBxhHBaFcjTppWelM0fQrTHrPAQy91w54=,tag:Dr3gvyRGAwNBXhumCSp+5Q==,type:str]
type: ENC[AES256_GCM,data:I+RLDxV/,iv:4ep00rRRIrmemXCSk8P+oL+MJBTr/UUBATndcnuDKxg=,tag:/hp4LPxrKRIm+d7NWIZz+Q==,type:str]
data:
    client_id: ENC[AES256_GCM,data:d4Cy7W7eJMryHQQG8IV7C6sqCg==,iv:mp1LF2ZIohpkY4FCCdVw15UJ1Q8krDiukjJqQKEmkp0=,tag:j7WNW2lIEsFq7PaH05P8dw==,type:str]
    client_secret: ENC[AES256_GCM,data:4cwExHaJF935WoYYKptRWQnpDJLcPjU=,iv:db+FzjcyfmouwOMZozcPmZSoOdT3c02ly3Hzc5E7+Qk=,tag:nYLSrWUFy5SQuqzH+hk6Wg==,type:str]
sops:
    age:
        - recipient: age1gzdqfgl6ww3en650g4dvtuejc0jrye60t7y34fxw6vm2mpj5g32quareev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WlF3aVpNekErbEZhb3VD
            b0pGb2c2MmhtQnRFUC8wbUtGRHMyV2VlWTJrCnQzdnhkMlNIcExxaWdTN3A4MnVy
            SVJTVnRXNkZDUWg0UVhpY3EzeEZ0RkEKLS0tIDZKSVdiYThxbndJcHVFR1ZNV01N
            Mi9uMGxEZU5TNGYrdnlDbHpyN1JGOWMKcV1s4po9EGfuGD/2jVknyxbLV767Kh2f
            7mwOLIoQj0DOW6RycJSMSrDk+7mZgvQea5e3kupo8cJkljgx/IKMAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T14:02:32Z"
    mac: ENC[AES256_GCM,data:3bq4ilLqgylE9Xl/IakF3bPydAqMClpQTkq4dx66e/haMwQvR2RQ0zHzj8mrD4N7RjgCVaJMVS0rXjlYg1xEqFuBjxIFOngVSqMEiilLRjtlKhFO5Tp3s0ChbUlRDbZrCDZMb2czog7gq3JafnQ4rCkJwgRoNADOlS3y7T73iYc=,iv:KLTcHdxlM2QxqjsgSqvyNoAuaAvb3ywV4j4qJlvIoNk=,tag:POIhxycingAA22AJ9f08sA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:/n8=,iv:37JzyZedlYkYRNn/4U/Tyujb3lR6HvZQubXe9hRApGY=,tag:pgs3L+0TyBL9UIzwtPPFKQ==,type:str]
kind: ENC[AES256_GCM,data:QFBw2Zlc,iv:ABg8BN9luNDo1FdqMdF1orJSRXtzGZUhkmcLo00G/Cg=,tag:E8vD+CRwS64I3C1UuH0rMw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:/yr2iWNEvkuu6rfOtI3avg7w,iv:68eTlT5SCplz34dT8S1JRhKBQuCDEl85dGyOGMkPSdM=,tag:PSDHjvAVFr20pL7L0lMFvQ==,type:str]
    namespace: ENC[AES256_GCM,data:v9OaWdM=,iv:WEUUNk9jIM+gE3ER+Wz1e2orMsYa9Ethmt8kAHMoZvw=,tag:rE8yBJXCO1wGQ1pjPUNVmw==,type:str]
type: ENC[AES256_GCM,data:gWhSJnNX,iv:qkOEMbXvjHujWCKO/LUD7QxxpSa+do4NYtKNfc1DjzM=,tag:k5ZOgHdOaZdYRYMAOY9qQQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:+avFNL3jXkQnrtzmEkvxUOc6KA==,iv:1REyZ2nGX3C3uaVGupnpdzYuntrZDIfBi47t3Fj64AY=,tag:khvUmmqd5dzn+eSSNLAy6A==,type:str]
    password: ENC[AES256_GCM,data:dZX/svDNjRPfaPB5bt7hlrxupOeBXktqgb1B,iv:LRBfFA4llZgXl6mLyCGaYBdJ49tAQge6wbsAmKF+dBs=,tag:7Du+LlQQ9TvhLCY4UiuAUg==,type:str]
sops:
    age:
        - recipient: age1gzdqfgl6ww3en650g4dvtuejc0jrye60t7y34fxw6vm2mpj5g32quareev
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WlF3aVpNekErbEZhb3VD
            b0pGb2c2MmhtQnRFUC8wbUtGRHMyV2VlWTJrCnQzdnhkMlNIcExxaWdTN3A4MnVy
            SVJTVnRXNkZDUWg0UVhpY3EzeEZ0RkEKLS0tIDZKSVdiYThxbndJcHVFR1ZNV01N
            Mi9uMGxEZU5TNGYrdnlDbHpyN1JGOWMKcV1s4po9EGfuGD/2jVknyxbLV767Kh2f
            7mwOLIoQj0DOW6RycJSMSrDk+7mZgvQea5e3kupo8cJkljgx/IKMAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T14:02:32Z"
    mac: ENC[AES256_GCM,data:3bq4ilLqgylE9Xl/IakF3bPydAqMClpQTkq4dx66e/haMwQvR2RQ0zHzj8mrD4N7RjgCVaJMVS0rXjlYg1xEqFuBjxIFOngVSqMEiilLRjtlKhFO5Tp3s0ChbUlRDbZrCDZMb2czog7gq3JafnQ4rCkJwgRoNADOlS3y7T73iYc=,iv:KLTcHdxlM2QxqjsgSqvyNoAuaAvb3ywV4j4qJlvIoNk=,tag:POIhxycingAA22AJ9f08sA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
