---
- name: Destroy old template to ensure a clean slate
  community.general.proxmox_kvm:
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_api_host }}"
    node: "{{ proxmox_node }}"
    vmid: "{{ alpine_vmid }}"
    state: absent
  delegate_to: localhost
  ignore_errors: true

- name: Download Alpine cloud image
  ansible.builtin.get_url:
    url: "{{ alpine_cloud_image_url }}"
    dest: "{{ alpine_cloud_image_path }}"
    mode: '0644'
  register: download_status
  until: download_status is succeeded
  retries: 5
  delay: 10

- name: Create Alpine VM for template
  community.general.proxmox_kvm:
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_api_host }}"
    node: "{{ proxmox_node }}"
    vmid: "{{ alpine_vmid }}"
    name: "{{ alpine_vm_name }}"
    agent: 1
    memory: "{{ alpine_ram }}"
    cores: "{{ alpine_cores }}"
    net:
      net0: "virtio,bridge={{ net_bridge }}"
    serial:
      serial0: socket
    vga: serial0
    scsihw: "virtio-scsi-pci"
    scsi:
      scsi0: "{{ disk_storage }}:0,import-from={{ alpine_cloud_image_path }}"
    ide:
      ide2: "{{ disk_storage }}:cloudinit"
    boot: "order=scsi0"
    cipassword: "{{ vm_password }}"
    ciuser: "{{ vm_user }}"
    sshkeys: "{{ vm_ssh_pub_key }}"
    template: true
    timeout: 600
  delegate_to: localhost
