---
# This task runs on the Ansible controller (your local machine)
- name: Install proxmoxer library locally
  ansible.builtin.pip:
    name: proxmoxer
    state: present
  delegate_to: localhost

- name: Install libguestfs-tools on proxmox
  ansible.builtin.package:
    name:
      - libguestfs-tools
    state: present

- name: Read SSH public key
  ansible.builtin.slurp:
    src: "{{ vm_ssh_pub_key }}"
  register: ssh_pub_key_content
  delegate_to: localhost


- name: Destroy old template to ensure a clean slate
  community.general.proxmox_kvm:
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_api_host }}"
    node: "{{ proxmox_node }}"
    vmid: "{{ vmid }}"
    state: absent
  delegate_to: localhost
  ignore_errors: true

# The following tasks run ON THE PROXMOX SERVER itself
# They use shell commands that only exist on the server
- name: Ensure qcow directory exists
  ansible.builtin.file:
    path: /var/lib/vz/template/qcow
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Download Debian 12 cloud image
  ansible.builtin.get_url:
    url: "{{ cloud_image_url }}"
    dest: "{{ cloud_image_path }}"
    mode: '0644'
  register: download_status
  until: download_status is succeeded
  retries: 5
  delay: 10

- name: Install qemu-guest-agent using virt-customize
  ansible.builtin.command:
    cmd: >
      virt-customize -a {{ cloud_image_path }}
      --install qemu-guest-agent
      --run-command "systemctl enable qemu-guest-agent"
      --run-command "systemctl start qemu-guest-agent"

- name: Create Debian 12 VM for template
  community.general.proxmox_kvm:
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_api_host }}"
    node: "{{ proxmox_node }}"
    vmid: "{{ vmid }}"
    name: "{{ vm_name }}"
    memory: 2048
    cores: 2
    net:
      net0: "virtio,bridge={{ net_bridge }}"
    serial:
      serial0: socket
    vga: serial0
    scsihw: "virtio-scsi-pci"
    scsi:
      scsi0: "{{ disk_storage }}:0,import-from={{ cloud_image_path }}"
    ide:
      ide2: "{{ disk_storage }}:cloudinit"
    boot: "order=scsi0"
    ciuser: "{{ cloud_user }}"
    sshkeys: "{{ ssh_pub_key_content.content | b64decode }}"
    template: true
    timeout: 600
  delegate_to: localhost
