---
- name: Download K3s install script
  get_url:
    url: https://get.k3s.io
    dest: /tmp/install-k3s.sh
    mode: '0755'

- name: Generate K3s cluster token
  run_once: true
  shell: "openssl rand -hex 16"
  register: k3s_cluster_token_raw
  delegate_to: localhost

- name: Store K3s cluster token
  run_once: true
  set_fact:
    k3s_cluster_token: "{{ k3s_cluster_token_raw.stdout }}"

- name: Run K3s install script (first master)
  when: inventory_hostname == groups['k3s_masters'][0]
  command: >
    sh /tmp/install-k3s.sh 
    --cluster-init 
    --token {{ k3s_cluster_token }} 
    --tls-san {{ haproxy_vip }}
    --disable traefik
  args:
    creates: /usr/local/bin/k3s

- name: Run K3s install script (other masters)
  when: inventory_hostname != groups['k3s_masters'][0]
  command: >
    sh /tmp/install-k3s.sh 
    --server https://{{ haproxy_vip }}:6443 
    --token {{ k3s_cluster_token }} 
    --tls-san {{ haproxy_vip }}
    --disable traefik
  args:
    creates: /usr/local/bin/k3s
