apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  values:
    authentik:
      secret_key: 'PleaseGenerateASecureKey'
      postgresql:
        password: 'LKz0EYm4ivI'
    postgresql:
      auth:
        password: 'LKz0EYm4ivI'