apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  values:
    authentik:
      secret_key: 'PleaseGenerateASecureKey' # trunk-ignore(trunk)
      postgresql:
        password: 'ThisIsNotASecurePassword'
    postgresql:
      auth:
        password: 'ThisIsNotASecurePassword' 