---
extends: default
rules:
  line-length:
    max: 200
    level: warning
  trailing-spaces: enable
  truthy:
    allowed-values: ['true', 'false', 'on']
  indentation:
    spaces: 2
    indent-sequences: consistent
  document-start:
    present: true
  comments:
    min-spaces-from-content: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 0
