---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
  namespace: falco
spec:
  interval: 5m
  chart:
    spec:
      chart: falco
      version: "5.x"
      sourceRef:
        kind: HelmRepository
        name: falco
        namespace: falco
  values:
    falco:
      json_output: true
      http_output:
        enabled: true
        url: http://falcosidekick.falcosidekick.svc.cluster.local:2801/