apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homelab-repo
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/ajdann/homelab.git
  ref:
    branch: main