---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  chart:
    spec:
      chart: authentik
      version: "2025.6.2"

  values:
    authentik:
      secret_key: "PleaseGenerateASecureKey"
      postgresql:
        password: "ThisIsNotASecurePassword"
    postgresql:
      auth:
        password: "ThisIsNotASecurePassword"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-provider
  namespace: authentik
data:
  gitea-provider.yaml: |
    version: 1
    metadata:
      name: gitea-oauth-provider
    entries:
      - model: authentik_providers_oauth2.oauth2provider
        attrs:
          client_id: u4QfKMnaRrcfipiNKOnrihhhA5U9Ik8shlhTviL6
          client_secret: UuWVUFWxY2Z9CA2F9BLNSnw4zpY46V84MTXMSGe6Tslx8h2y8rWefZIspMsvVQ97zKH0UnJlVepU2RmGdhiMjzMeY1i9AuKZzMrAIAKqBFGYqnT1nxUuT1GANDWds1RP
