---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: policy-reporter
  namespace: policy-reporter
spec:
  chart:
    spec:
      chart: policy-reporter
      version: "2.21.0"
