apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - target:
      kind: HelmRelease
      name: authentik
      namespace: authentik
    patch: |-
      - op: replace
        path: /spec/chart/spec/version
        value: "2025.6.2"
      - op: add
        path: /spec/values
        value:
          authentik:
            secret_key: "PleaseGenerateASecureKey"
            postgresql:
              password: "ThisIsNotASecurePassword"
          postgresql:
            auth:
              password: "ThisIsNotASecurePassword"

  - target:
      kind: ConfigMap
      name: gitea-provider
      namespace: authentik
    patch: |-
      - op: add
        path: /data
        value:
          gitea-provider.yaml: |
            version: 1
            metadata:
              name: gitea-oauth-provider
            entries:
              - model: authentik_providers_oauth2.oauth2provider
                attrs:
                  client_id: u4QfKMnaRrcfipiNKOnrihhhA5U9Ik8shlhTviL6
                  client_secret: UuWVUFWxY2Z9CA2F9BLNSnw4zpY46V84MTXMSGe6Tslx8h2y8rWefZIspMsvVQ97zKH0UnJlVepU2RmGdhiMjzMeY1i9AuKZzMrAIAKqBFGYqnT1nxUuT1GANDWds1RP
