---
- name: Deploy Wazuh agent with host monitoring
  hosts: localhost
  become: true
  vars:
    wazuh_manager_ip: "192.168.56.10"   # NodePort of Wazuh manager service
    wazuh_manager_port: 31515           # NodePort mapped to 31515
    wazuh_api_port: 32000               # NodePort mapped to 32000 for API
    wazuh_agent_name: "{{ inventory_hostname }}"
    wazuh_api_secret_name: "wazuh-api-cred"
    wazuh_api_secret_namespace: "wazuh"

  tasks:
    - name: Ensure .kube directory exists
      file:
        path: "/home/{{ lookup('env','USER') }}/.kube"
        state: directory
        owner: "{{ lookup('env','USER') }}"
        group: "{{ lookup('env','USER') }}"
        mode: '0700'

    - name: Copy kubeconfig for Ansible
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "/home/{{ lookup('env','USER') }}/.kube/config"
        remote_src: true
        owner: "{{ lookup('env','USER') }}"
        group: "{{ lookup('env','USER') }}"
        mode: '0600'

    - name: Fetch Wazuh API secret from Kubernetes
      kubernetes.core.k8s:
        api_version: v1
        kind: Secret
        name: "{{ wazuh_api_secret_name }}"
        namespace: "{{ wazuh_api_secret_namespace }}"
        kubeconfig: "/home/{{ lookup('env','USER') }}/.kube/config"
        state: present
      register: wazuh_api_secret

    - name: Decode Wazuh API username and password
      set_fact:
        wazuh_api_username: "{{ wazuh_api_secret.result.data.username | b64decode }}"
        wazuh_api_password: "{{ wazuh_api_secret.result.data.password | b64decode }}"

    - name: Add Wazuh repository GPG key
      ansible.builtin.apt_key:
        url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
        state: present

    - name: Add Wazuh repository
      ansible.builtin.apt_repository:
        repo: "deb https://packages.wazuh.com/4.x/apt/ stable main"
        state: present
        filename: wazuh

    - name: Install Wazuh agent and dependencies
      ansible.builtin.apt:
        name:
          - wazuh-agent
          - auditd
          - lsb-release
        state: present
        update_cache: yes

    - name: Ensure ossec group exists
      ansible.builtin.group:
        name: ossec
        state: present

    - name: Ensure ossec user exists
      ansible.builtin.user:
        name: ossec
        group: ossec
        system: yes
        shell: /sbin/nologin
        state: present
        
    - name: Configure Wazuh agent
      template:
        src: wazuh-agent.conf.j2
        dest: /var/ossec/etc/ossec.conf
        owner: ossec
        group: ossec
        mode: '0660'

    - name: Ensure ossec.conf is owned by ossec
      ansible.builtin.file:
        path: /var/ossec/etc/ossec.conf
        owner: ossec
        group: ossec
        mode: '0640'

    - name: Ensure Wazuh agent service is enabled and running
      ansible.builtin.systemd:
        name: wazuh-agent
        enabled: true
        state: started
        daemon_reload: true

    - name: Ensure auditd service is enabled and running
      ansible.builtin.systemd:
        name: auditd
        enabled: true
        state: started

    - name: Get Wazuh API token
      uri:
        url: "https://{{ wazuh_manager_ip }}:{{ wazuh_api_port }}/security/user/authenticate"
        method: POST
        user: "{{ wazuh_api_username }}"
        password: "{{ wazuh_api_password }}"
        force_basic_auth: yes
        return_content: yes
        validate_certs: no
      register: wazuh_api_response

    - name: Register Wazuh agent via API
      uri:
        url: "https://{{ wazuh_manager_ip }}:{{ wazuh_api_port }}/agents"
        method: POST
        headers:
          Authorization: "Bearer {{ wazuh_api_response.json.data.token }}"
        body_format: json
        body:
          name: "{{ wazuh_agent_name }}"
          ip: "{{ ansible_default_ipv4.address }}"
        return_content: yes
        validate_certs: no
      register: wazuh_agent_registration
