---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 5m
  chart:
    spec:
      chart: nextcloud
      version: '7.0.0'
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: nextcloud
  values: 
    ingress:
      enabled: true
      className: "tailscale"
      annotations:
        tailscale.com/tags: tag:k8s-operator
        gethomepage.dev/enabled: 'true'
        gethomepage.dev/name: 'Nextcloud'
        gethomepage.dev/description: 'File storage'
        gethomepage.dev/group: 'Homelab Services'
        gethomepage.dev/icon: 'nextcloud.png'
        gethomepage.dev/href: 'https://nextcloud.tail1345c.ts.net'
        # For loadbalance over multiple Pods, it is useful to configure sticky session
        # nginx.ingress.kubernetes.io/affinity: cookie
        # traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
        # haproxy-ingress.github.io/affinity: cookie
      hosts:
      - host: nextcloud
        paths:
        - path: /
          pathType: ImplementationSpecific
      tls: 
        - hosts:
          - nextcloud
    nextcloud:
      host: 'nextcloud'
      trustedDomains: 
        - 'nextcloud.tail1345c.ts.net'
        - 'nextcloud'
      existingSecret:
        enabled: true
        secretName: nextcloud-admin-credentials
        usernameKey: username
        passwordKey: password