---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: auto-add-security-context
  annotations:
    policies.kyverno.io/title: Auto Add Security Context
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      This policy automatically adds security contexts to pods that don't have them, improving security without requiring manual configuration.
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: add-security-context
    match:
      any:
      - resources:
          kinds:
          - Pod
    mutate:
      patchStrategicMerge:
        spec:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            fsGroup: 1000
          containers:
          - (securityContext):
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 1000
              capabilities:
                drop:
                - ALL
