---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: policy-reporter
  namespace: policy-reporter
spec:
  interval: 5m
  chart:
    spec:
      chart: policy-reporter
      version: "2.21.0"
      sourceRef:
        kind: HelmRepository
        name: policy-reporter
        namespace: policy-reporter
      interval: 1m
  values:
    ui:
      enabled: true
    persistence:
      enabled: false
    service:
      type: ClusterIP
    ingress:
      enabled: true
      className: tailscale
      annotations:
        tailscale.com/tags: tag:k8s-operator
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Policy Reporter"
        gethomepage.dev/description: "Kyverno policy results dashboard"
        gethomepage.dev/group: "Homelab Services"
        gethomepage.dev/icon: "shield-check-outline"
        gethomepage.dev/href: "https://policy-reporter.tail1345c.ts.net"
        gethomepage.dev/widget.type: "policy-reporter"
        gethomepage.dev/widget.url: "https://policy-reporter.tail1345c.ts.net"
      hosts:
      - host: policy-reporter
        paths:
        - /
      tls:
      - hosts:
        - policy-reporter
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi
