---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "76.4.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: prometheus
  values:
    prometheus:
      prometheusSpec:
        resources:
          requests:
            memory: 512Mi
            cpu: 200m
          limits:
            memory: 1Gi
            cpu: 400m
        storageSpec:
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 2Gi
        retention: 7d
        # scrape interval adjustment
        scrapeInterval: 60s
        evaluationInterval: 60s
    alertmanager:
      alertmanagerSpec:
        resources:
          requests:
            memory: 128Mi
            cpu: 50m
          limits:
            memory: 256Mi
            cpu: 100m
        storage:
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 500Mi
    grafana:
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 200m
    kubeStateMetrics:
      resources:
        requests:
          memory: 64Mi
          cpu: 25m
        limits:
          memory: 128Mi
          cpu: 50m
    nodeExporter:
      resources:
        requests:
          memory: 50Mi
          cpu: 25m
        limits:
          memory: 100Mi
          cpu: 50m