---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus
      version: "27.30.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: prometheus
  values: