---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
  namespace: keda
spec:
  interval: 5m
  chart:
    spec:
      chart: keda
      version: "2.13.0"
      sourceRef:
        kind: HelmRepository
        name: kedacore
        namespace: keda
  values:
    # Enable CRDs installation
    installCRDs: true
    # Enable metrics server
    metricsServer:
      enabled: true
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
          - ALL
        seccompProfile:
          type: RuntimeDefault
    # Enable webhooks
    webhooks:
      enabled: true
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
          - ALL
        seccompProfile:
          type: RuntimeDefault
    # Enable all scalers
    operator:
      extraArgs:
      - --enable-scalers=http
      - --enable-scalers=cron
      - --enable-scalers=cpu
      - --enable-scalers=memory
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
          - ALL
        seccompProfile:
          type: RuntimeDefault
