---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda-http-add-on
  namespace: keda
spec:
  interval: 5m
  chart:
    spec:
      chart: keda-add-ons-http
      version: "0.7.2"
      sourceRef:
        kind: HelmRepository
        name: kedacore
        namespace: keda
  values: {}
