---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - kured
- tailscale
- dashboard
- reloader
- kubescape
# - netdata
# - keda
# - kyverno
# - policy-reporter
# - falco
# - prometheus
