---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kured
spec:
  interval: 5m
  chart:
    spec:
      chart: kured
      version: "5.x"
      sourceRef:
        kind: HelmRepository
        name: kured
        namespace: kured
  values:
    configuration:
      startTime: "3:00"
      endTime: "5:00"
      timeZone: "UTC"
      rebootMethod: "signal"
      rebootSignal: "39"
      period: "1h"
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
    containerSecurityContext:
      privileged: false
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      capabilities:
        add:
        - CAP_KILL
        drop:
        - ALL
      seccompProfile:
        type: RuntimeDefault
