apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kured
spec:
  interval: 5m
  chart:
    spec:
      chart: kured
      version: "5.x"
      sourceRef:
        kind: HelmRepository
        name: kured
        namespace: kured
  values:
    configuration:
      startTime: "3:00"
      endTime: "5:00"
      timeZone: "UTC"
      rebootCommand: "/usr/bin/systemctl reboot"
      period: "1h" 