---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falcosidekick
  namespace: falcosidekick
spec:
  interval: 5m
  chart:
    spec:
      chart: falcosidekick
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: falcosidekick
  values:
    replicaCount: 1

    # Pod Security Context
    podSecurityContext:
      runAsUser: 1234
      runAsGroup: 1234
      fsGroup: 1234
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault

    # Container Security Context
    securityContext:
      allowPrivilegeEscalation: false
      privileged: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true

    # Resource limits
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi

    config:
      # Debug mode
      debug: false

      # Falco event forwarding endpoint
      # This is the webhook URL where Falco will send events
      # By default, Falcosidekick listens on http://falcosidekick:2801

      # Customize outputs here based on your needs
      # Examples:
      # slack:
      #   webhookurl: ""
      #   minimumpriority: ""
      #
      loki:
        hostport: "http://loki.monitoring.svc.cluster.local:3100"
        minimumpriority: ""
      #
      # elasticsearch:
      #   hostport: "http://elasticsearch:9200"
      #   minimumpriority: ""
      #
      # alertmanager:
      #   hostport: "http://alertmanager:9093"
      #   minimumpriority: ""

    # Service configuration
    service:
      type: ClusterIP
      port: 2801

    # Ingress configuration
    ingress:
      enabled: false

    # Web UI configuration (if enabled)
    webui:
      enabled: false
