---
# Kubeconfig Management Tasks

- name: Resolve absolute kubeconfig destination path
  set_fact:
    kubeconfig_absolute_path: "{{ kubeconfig_dest_path | realpath }}"
  delegate_to: localhost
  run_once: true
  when: inventory_hostname == groups['k3s_masters'][0]

- name: Fetch kubeconfig file
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ kubeconfig_dest_path }}"
    flat: yes
  become: true
  when: inventory_hostname == groups['k3s_masters'][0]
  register: kubeconfig_fetch_result
  failed_when: kubeconfig_fetch_result.failed

- name: Display kubeconfig file path
  debug:
    msg: "Kubeconfig file saved to absolute path: {{ kubeconfig_absolute_path }}"
  delegate_to: localhost
  when: inventory_hostname == groups['k3s_masters'][0]

- name: Determine kubeconfig server endpoint
  set_fact:
    k3s_kubeconfig_server: "{{ kubeconfig_server | default(kubeconfig_server_default) }}"
  delegate_to: localhost
  run_once: true
  when: inventory_hostname == groups['k3s_masters'][0]

- name: Update kubeconfig with server endpoint
  replace:
    path: "{{ kubeconfig_dest_path }}"
    regexp: 'server: https://.*:6443'
    replace: "server: https://{{ k3s_kubeconfig_server }}:6443"
  delegate_to: localhost
  run_once: true
  when: inventory_hostname == groups['k3s_masters'][0]
  register: kubeconfig_update_result
  failed_when: kubeconfig_update_result.failed