---
# K3s Server Role - Main Tasks
# This role installs and configures K3s in server mode with proper clustering support

- name: Validate prerequisites and input parameters
  ansible.builtin.import_tasks: validate.yaml
  tags: ['k3s', 'k3s-validate']

- name: Install K3s server
  ansible.builtin.import_tasks: install.yaml
  tags: ['k3s', 'k3s-install']

- name: Manage kubeconfig
  ansible.builtin.import_tasks: kubeconfig.yaml
  tags: ['k3s', 'k3s-kubeconfig']

- name: Verify K3s installation
  ansible.builtin.import_tasks: verify.yaml
  tags: ['k3s', 'k3s-verify']
