---
# K3s Service Verification Tasks

- name: Verify K3s service is running
  service:
    name: k3s
    state: started
    enabled: true
  become: true
  register: k3s_service_result
  failed_when: k3s_service_result.failed

- name: Wait for K3s API to be ready
  wait_for:
    port: 6443
    host: "{{ kubernetes_vip }}"
    timeout: "{{ k3s_service_start_timeout }}"
  when: inventory_hostname == groups['k3s_masters'][0]

- name: Verify K3s cluster is accessible using k3s kubectl
  command: k3s kubectl get nodes
  register: k3s_cluster_check
  failed_when: k3s_cluster_check.rc != 0
  when: inventory_hostname == groups['k3s_masters'][0]
  retries: "{{ k3s_api_check_retries }}"
  delay: "{{ k3s_api_check_delay }}"
  become: true

- name: Verify K3s cluster has ready nodes
  command: k3s kubectl get nodes --no-headers
  register: k3s_nodes_check
  failed_when: "'Ready' not in k3s_nodes_check.stdout"
  when: inventory_hostname == groups['k3s_masters'][0]
  become: true

- name: Display K3s cluster status
  debug:
    msg: 
      - "K3s cluster is ready!"
      - "Cluster nodes:"
      - "{{ k3s_cluster_check.stdout_lines }}"
  when: 
    - inventory_hostname == groups['k3s_masters'][0]
    - k3s_cluster_check is defined