---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: policy-reporter
  namespace: policy-reporter
spec:
  interval: 5m
  chart:
    spec:
      chart: policy-reporter
      version: "2.21.0"
      sourceRef:
        kind: HelmRepository
        name: policy-reporter
        namespace: policy-reporter
      interval: 1m
  values:
    ui:
      enabled: true
    persistence:
      enabled: false
    service:
      type: ClusterIP
    ingress:
      enabled: false
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi
