---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: policy-reporter
  namespace: policy-reporter
spec:
  interval: 1h
  url: https://kyverno.github.io/policy-reporter
