apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-provider
  namespace: authentik
data:
  gitea-provider.yaml: |
    # yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
    version: 1
    metadata:
      name: gitea-oauth-provider
    entries:
      - model: authentik_providers_oauth2.oauth2provider
        state: present
        identifiers:
          name: gitea-provider
        attrs:
          name: gitea-provider
          client_id: "CLIENT_ID_PLACEHOLDER"
          client_secret: "CLIENT_SECRET_PLACEHOLDER"
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
          invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
          redirect_uris:
            - url: https://gitea.tail1345c.ts.net/user/oauth2/authentik/callback
              matching_mode: strict
          signing_key: !Find [authentik_crypto.certificatekeypair, [name, default]]
          access_token_validity: hours=1
          refresh_token_validity: days=1
          include_in_api: true
          token_validity: hours=1
          include_claims_in_id_token: true
          sub_mode: hashed_user_id
          property_mappings:
            - !Find [authentik_providers_oauth2.scopemapping, [name, "authentik default OAuth Mapping: OpenID 'email'"]]
            - !Find [authentik_providers_oauth2.scopemapping, [name, "authentik default OAuth Mapping: OpenID 'profile'"]]
            - !Find [authentik_providers_oauth2.scopemapping, [name, "authentik default OAuth Mapping: OpenID 'openid'"]]
            - !Find [authentik_providers_oauth2.scopemapping, [name, "authentik gitea OAuth Mapping: OpenID 'gitea'"]]
