---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  interval: 5m
  chart:
    spec:
      chart: gitea
      version: '12.0.0'
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: gitea
  values:
    replicaCount: 1
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 512Mi
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      seccompProfile:
        type: RuntimeDefault
    containerSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      allowPrivilegeEscalation: false
      privileged: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      seccompProfile:
        type: RuntimeDefault
    initContainers:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        allowPrivilegeEscalation: false
        privileged: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: false
        seccompProfile:
          type: RuntimeDefault
    gitea:
      oauth:
        - name: 'authentik'
          provider: 'openidConnect'
          existingSecret: gitea-authentik-secret
          autoDiscoverUrl: 'http://authentik-server.authentik.svc.cluster.local/application/o/gitea-app/.well-known/openid-configuration'
          iconUrl: 'http://authentik-server.authentik.svc.cluster.local/static/dist/assets/icons/icon.png'
          scopes: 'openid email profile'
          # required_claim_value: "" # Leave empty if no specific value is required
          # required_claim_name: "gitea"
          # group_claim_name: "gitea"
          # admin_group: "admin"
          # restricted_group: "restricted"
          # requiredClaimValue: "" # Leave empty if no specific value is required
          # requiredClaimName: "gitea"
          # groupClaimName: "gitea"
          # adminGroup: "admin"
          # restrictedGroup: "restricted"
      config:
        server:
          DOMAIN: gitea.tail1345c.ts.net
          ROOT_URL: https://gitea.tail1345c.ts.net/
          DISABLE_SSH: true
          ENABLE_AUTO_REGISTRATION: 'true'
        database:
          DB_TYPE: sqlite3
        session:
          PROVIDER: memory
        cache:
          ADAPTER: memory
        queue:
          TYPE: level
        security:
          INSTALL_LOCK: true
        admin:
          existingSecret: gitea-admin-secret
        startupProbe:
          enabled: true
        readinessProbe:
          enabled: true
        livenessProbe:
          enabled: true
    persistence:
      enabled: false
      size: 10Gi
    service:
      http:
        type: ClusterIP
        port: 3000
        clusterIP:
    ingress:
      enabled: true
      className: tailscale
      annotations:
        tailscale.com/tags: tag:k8s-operator
        gethomepage.dev/enabled: 'true'
        gethomepage.dev/name: 'Gitea'
        gethomepage.dev/description: 'Git repository management'
        gethomepage.dev/group: 'Homelab Services'
        gethomepage.dev/icon: 'gitea.png'
        gethomepage.dev/href: 'https://gitea.tail1345c.ts.net'
        # gethomepage.dev/widget.url: 'https://gitea.tail1345c.ts.net'
        # gethomepage.dev/pod-selector: 'app.kubernetes.io/name=gitea'
      hosts:
        - host: gitea
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - gitea
    valkey-cluster:
      enabled: false
    valkey:
      enabled: false
    postgresql:
      enabled: false
    postgresql-ha:
      enabled: false
