---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  interval: 5m
  chart:
    spec:
      chart: gitea
      version: "12.0.0"
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: gitea
  values:
    replicaCount: 0
    gitea:
      config:
        server:
          DOMAIN: gitea
          ROOT_URL: https://gitea/
          DISABLE_SSH: true
        database:
          DB_TYPE: sqlite3
          PATH: /data/gitea/gitea.db
        security:
          INSTALL_LOCK: true
        admin:
          username: admin
          password: admin123
          email: admin@gitea.local
    persistence:
      enabled: true
      size: 10Gi
    service:
      http:
        type: ClusterIP
        port: 3000
        clusterIP:
    ingress:
      enabled: true
      className: tailscale
      annotations:
        tailscale.com/tags: tag:k8s-operator
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Gitea"
        gethomepage.dev/description: "Git repository management"
        gethomepage.dev/group: "Homelab Services"
        gethomepage.dev/icon: "gitea.png"
        gethomepage.dev/href: "https://gitea.tail1345c.ts.net"
        gethomepage.dev/widget.url: "https://gitea.tail1345c.ts.net"
        gethomepage.dev/pod-selector: "app.kubernetes.io/name=gitea"
      hosts:
      - host: gitea
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - gitea
    postgresql-ha:
      enabled: true
    postgresql:
      enabled: false
    valkey-cluster:
      enabled: true
      cluster:
        nodes: 1
        replicas: 0
    valkey:
      enabled: false
      master:
        count: 1
