---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  interval: 5m
  chart:
    spec:
      chart: gitea
      version: "9.4.0"
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: gitea
  values:
    gitea:
      config:
        server:
          DOMAIN: gitea.local
          ROOT_URL: http://gitea.local/
          DISABLE_SSH: true
        database:
          DB_TYPE: sqlite3
          PATH: /data/gitea/gitea.db
        security:
          INSTALL_LOCK: true
        admin:
          username: admin
          password: admin123
          email: admin@gitea.local
    persistence:
      enabled: true
      size: 10Gi
    service:
      http:
        type: ClusterIP
        port: 3000
    ingress:
      enabled: true
      className: tailscale
      hosts:
      - host: gitea.local
        paths:
        - path: /
          pathType: Prefix
      tls: []
