---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  interval: 5m
  chart:
    spec:
      chart: gitea
      version: "12.0.0"
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: gitea
  values:
    replicaCount: 0
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 512Mi
    podSecurityContext:
      fsGroup: 1000
    initContainers:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    gitea:
      config:
        server:
          DOMAIN: gitea
          ROOT_URL: https://gitea/
          DISABLE_SSH: true
        database:
          DB_TYPE: sqlite3
        session:
          PROVIDER: memory
        cache:
          ADAPTER: memory
        queue:
          TYPE: level
        security:
          INSTALL_LOCK: true
        admin:
          username: admin
          password: admin123
          email: admin@gitea.local
        startupProbe:
          enabled: true
        readinessProbe:
          enabled: true
        livenessProbe:
          enabled: true
    persistence:
      enabled: true
      size: 10Gi
    service:
      http:
        type: ClusterIP
        port: 3000
        clusterIP:
    ingress:
      enabled: true
      className: tailscale
      annotations:
        tailscale.com/tags: tag:k8s-operator
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Gitea"
        gethomepage.dev/description: "Git repository management"
        gethomepage.dev/group: "Homelab Services"
        gethomepage.dev/icon: "gitea.png"
        gethomepage.dev/href: "https://gitea.tail1345c.ts.net"
        gethomepage.dev/widget.url: "https://gitea.tail1345c.ts.net"
        gethomepage.dev/pod-selector: "app.kubernetes.io/name=gitea"
      hosts:
      - host: gitea
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - gitea
    valkey-cluster:
      enabled: false
    valkey:
      enabled: false
    postgresql:
      enabled: false
    postgresql-ha:
      enabled: false

