---
apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: gitea-http-scaler
  namespace: gitea
spec:
  host: gitea.tail1345c.ts.net
  targetPendingRequests: 100
  scaledownPeriod: 300
  scaleTargetRef:
    deployment: gitea
    service: gitea-http
    port: 3000
  replicas:
    min: 0
    max: 3
