---
- name: Add Wazuh GPG key
  apt_key:
    url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    state: present

- name: Add Wazuh repository
  apt_repository:
    repo: "deb https://packages.wazuh.com/4.x/apt/ stable main"
    state: present
    filename: wazuh

- name: Install Wazuh agent (specific version to match manager)
  apt:
    name: "wazuh-agent=4.12.0-1"
    state: present
    update_cache: yes
    allow_downgrade: yes
