apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homelab
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kubernetes/clusters/homelab
  prune: true
  force: true
  sourceRef:
    kind: GitRepository
    name: homelab-repo
  wait: true
  timeout: 2m
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-substitutions
