---
- name: Deploy K3s HA cluster
  hosts: k3s_masters
  gather_facts: true
  become: true
  roles:
    - ../roles/node_bootstrap
    - ../roles/k3s_server
    # - ../roles/tailscale_agent
  vars_files:
    - ../group_vars/all.yaml
