name: Kustomize Validation
on:
  push:
    branches: [main, master]
    paths: ['kubernetes/**']
  pull_request:
    branches: [main, master]
    paths: ['kubernetes/**']

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Kustomize configurations
        run: |
          echo "Validating prod overlay..."
          kustomize build kubernetes/overlays/prod --dry-run

          echo "Validating dev overlay..."
          kustomize build kubernetes/overlays/dev --dry-run

          echo "✅ All Kustomize configurations are valid!"

      - name: Check for unused resources
        run: |
          echo "Checking for unused resources..."
          # This would require additional tooling like kustomize-unused
          # For now, just validate the builds work
          echo "✅ Resource validation complete!"
