apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubescape-operator
  namespace: kubescape
spec:
  interval: 5m
  chart:
    spec:
      chart: kubescape-operator
      version: '1.29.6'
      sourceRef:
        kind: HelmRepository
        name: kubescape
        namespace: kubescape
  values:
    clusterName: "homelab"
    capabilities:
      continuousScan: "enable"
